name: Deploy Server Docker Image

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'frontend/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build_server
        uses: docker/build-push-action@v3
        with:
          file: server.Dockerfile
          context: .
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Only push if on main branch
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: |
            ghcr.io/marigold-dev/server:latest
            ghcr.io/marigold-dev/server:${{ github.sha }}

